version: '3'

services:
  brevetsapp:
    build: brevetsapp/     
    command: python -u flask_brevets.py
    ports: 
      - "7260:5000"
    depends_on:
      - tododb
    environment:
        MONGODB_HOSTNAME: tododb
  restapi:
    build: api/
    command: python -u api.py
    ports: 
      - "7261:5000"
    depends_on:
      - tododb
    environment:
        MONGODB_HOSTNAME: tododb
  website:
    build: website/
    command: python -u flaskLogin.py password.py testToken.py
    ports:
      - "7262:5000"
    depends_on:
      - restapi
      - tododb
    environment:
        MONGODB_HOSTNAME: tododb
        BACKEND_ADDR: restapi
        BACKEND_PORT: 5000
  tododb:
    image: mongo:latest
    
